
/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries

SELECT country,COUNT(customer_key) AS total_customers FROM gold_dim_customers 
GROUP by country ORDER BY COUNT(customer_key) DESC;

-- Find total customers by gender

SELECT gender,COUNT(customer_key) AS total_customers FROM gold_dim_customers 
GROUP by gender ORDER BY COUNT(customer_key) DESC;

-- Find total products by category

SELECT category,COUNT(product_key) AS total_products FROM gold_dim_products 
GROUP by category ORDER BY COUNT(product_key) DESC;

-- What is the average costs in each category?

SELECT category,AVG(product_cost) AS avg_cost FROM gold_dim_products 
GROUP BY category ORDER BY AVG(product_cost) DESC;
-- What is the total revenue generated for each category?
 
 SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
-- What is the total revenue generated by each customer?

SELECT
    c.customer_key,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales AS f
LEFT JOIN gold_dim_customers AS  c
    ON c.customer_key = f.customer_key
GROUP BY c.customer_key
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?

SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold_fact_sales AS f
LEFT JOIN gold_dim_customers AS  c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
